import { ArrowUpRight, Mail, MapPin, MessageCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { footerLinks } from "@/lib/site";

export default function SiteFooter() {
  return <footer data-testid="site-footer" className="bg-[#241b18] px-5 py-16 text-[#f7f1e8] md:px-10 md:py-20">
    <div className="mx-auto max-w-[1360px]">
      <div className="grid gap-12 border-b border-[#f7f1e8]/15 pb-14 md:grid-cols-[1.2fr_.8fr_.8fr]">
        <div><Link to="/" data-testid="footer-logo-link" className="inline-flex items-center gap-3"><span data-testid="footer-logo-mark" className="font-japanese text-3xl text-[#e7c36d]">日</span><span data-testid="footer-logo-wordmark" className="font-display text-3xl">RSP in Japan</span></Link><p data-testid="footer-tagline" className="mt-5 max-w-sm text-sm leading-7 text-[#f7f1e8]/60">A patient path from Japanese language learning in India to study, work, and belonging in Japan.</p><p data-testid="footer-founded-line" className="mt-7 text-[10px] font-bold uppercase tracking-[0.16em] text-[#e7c36d]">Founded 2020 by Rohit Shiv Prasad · Kyoto</p></div>
        <div><p data-testid="footer-links-label" className="mb-5 text-[10px] font-bold uppercase tracking-[0.24em] text-[#e7c36d]">Explore</p><nav aria-label="Footer navigation" className="grid gap-3">{footerLinks.map((item) => <Link key={item.href} to={item.href} data-testid={`footer-nav-${item.label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`} className="w-fit text-sm text-[#f7f1e8]/70 transition-colors duration-200 hover:text-[#fffaf2]">{item.label}</Link>)}</nav></div>
        <div><p data-testid="footer-contact-label" className="mb-5 text-[10px] font-bold uppercase tracking-[0.24em] text-[#e7c36d]">Stay connected</p><div className="grid gap-4 text-sm text-[#f7f1e8]/70"><a href="mailto:rspinjapan@gmail.com" data-testid="footer-email-link" className="flex items-center gap-3 hover:text-[#fffaf2]"><Mail size={15} /> rspinjapan@gmail.com</a><a href="https://wa.me/919999999999" data-testid="footer-whatsapp-link" className="flex items-center gap-3 hover:text-[#fffaf2]"><MessageCircle size={15} /> WhatsApp Rohit</a><p data-testid="footer-locations" className="flex items-start gap-3"><MapPin size={15} className="mt-0.5 shrink-0" />Kyoto, Japan<br />Meerut, India</p></div><div className="mt-6 flex gap-3"><a href="https://www.linkedin.com" target="_blank" rel="noreferrer" data-testid="footer-linkedin-link" aria-label="RSP on LinkedIn" className="rounded-full border border-[#f7f1e8]/20 p-2 hover:border-[#e7c36d] hover:text-[#e7c36d]"><ArrowUpRight size={15} /></a><a href="https://www.instagram.com" target="_blank" rel="noreferrer" data-testid="footer-instagram-link" aria-label="RSP on Instagram" className="rounded-full border border-[#f7f1e8]/20 p-2 hover:border-[#e7c36d] hover:text-[#e7c36d]"><ArrowUpRight size={15} /></a></div></div>
      </div>
      <div className="flex flex-col justify-between gap-3 pt-6 text-[10px] uppercase tracking-[0.16em] text-[#f7f1e8]/40 sm:flex-row"><p data-testid="footer-copyright">© 2025 RSP in Japan. All rights reserved.</p><p data-testid="footer-note">Japanese language · JLPT · Japan pathways</p></div>
    </div>
  </footer>;
}