import { HeartHandshake, ShieldCheck, Sparkles } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import SectionHeading from "@/components/site/SectionHeading";
import SiteLayout from "@/components/site/SiteLayout";
import { timeline } from "@/lib/site";

const values: Array<{ number: string; title: string; detail: string; icon: LucideIcon }> = [
  { number: "01", title: "Discipline", detail: "Progress is rarely loud. It is the quiet decision to return to practice, again and again.", icon: ShieldCheck },
  { number: "02", title: "Cultural respect", detail: "Language opens a door, but respect teaches you how to enter a place with care.", icon: HeartHandshake },
  { number: "03", title: "Real outcomes", detail: "A certificate matters. So does the confidence to use Japanese in school, work, and everyday life.", icon: Sparkles },
];

export default function About() {
  return <SiteLayout>
    <section data-testid="about-hero" className="bg-[#a80000] px-5 pb-20 pt-40 text-[#fffaf2] md:px-10 md:pb-28 md:pt-48"><div className="mx-auto grid max-w-[1360px] gap-10 md:grid-cols-[.7fr_1.3fr] md:items-end"><p data-testid="about-hero-japanese" className="font-japanese text-8xl text-[#e7c36d]/70 md:text-[12rem]">道</p><div><p data-testid="about-hero-eyebrow" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[#e7c36d]">Our story · Since 2020</p><h1 data-testid="about-hero-heading" className="mt-5 max-w-4xl font-display text-6xl leading-[.92] tracking-[-.06em] md:text-8xl">Five years.<br /><span className="text-[#e7c36d]">One clear path.</span></h1><p data-testid="about-hero-copy" className="mt-7 max-w-xl text-sm leading-7 text-[#f7f1e8]/75">RSP in Japan began with a simple belief: students deserve an honest, human bridge between where they are and the life they are working toward.</p></div></div></section>
    <section data-testid="about-company-section" className="bg-[#fffaf2] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1360px]"><SectionHeading eyebrow="About the company" title="Five years of turning intention into movement." description="Founded in 2020, RSP in Japan has helped more than 50 students move toward Yokohama language school, JLPT progression from N3 to N1, and new work possibilities in Japan." /><div className="mt-16 max-w-4xl border-l border-[#a80000]/25">{timeline.map((item, index) => <div key={item.year} data-testid={`about-timeline-${index}`} className="relative grid gap-2 border-b border-[#a80000]/15 px-7 py-7 last:border-0 md:grid-cols-[120px_1fr] md:gap-8"><span className="absolute -left-[5px] top-9 h-2 w-2 rounded-full bg-[#a80000] ring-4 ring-[#fffaf2]" /><p data-testid={`about-timeline-year-${index}`} className="font-display text-2xl text-[#a80000]">{item.year}</p><div><h3 data-testid={`about-timeline-title-${index}`} className="font-display text-2xl">{item.title}</h3><p data-testid={`about-timeline-detail-${index}`} className="mt-2 text-sm leading-7 text-[#756862]">{item.detail}</p></div></div>)}</div></div></section>
    <section data-testid="about-values-section" className="wash-pattern px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1360px]"><SectionHeading eyebrow="What we believe" title="The values that keep the path real." /><div className="mt-14 grid gap-5 md:grid-cols-3">{values.map(({ number, title, detail, icon: ValueIcon }) => <article key={number} data-testid={`about-value-card-${number}`} className="border-t border-[#a80000]/25 pt-5"><div className="flex justify-between"><ValueIcon size={21} className="text-[#a80000]" /><span className="font-display text-3xl text-[#a80000]/25">{number}</span></div><h3 data-testid={`about-value-title-${number}`} className="mt-14 font-display text-3xl">{title}</h3><p data-testid={`about-value-detail-${number}`} className="mt-4 text-sm leading-7 text-[#756862]">{detail}</p></article>)}</div></div></section>
  </SiteLayout>;
}