import { ArrowUpRight, Award, HeartHandshake, ShieldCheck, Sparkles } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import Placeholder from "@/components/site/Placeholder";
import SectionHeading from "@/components/site/SectionHeading";
import SiteLayout from "@/components/site/SiteLayout";
import { timeline } from "@/lib/site";

const values: Array<{ number: string; title: string; detail: string; icon: LucideIcon }> = [
  { number: "01", title: "Discipline", detail: "Progress is rarely loud. It is the quiet decision to return to practice, again and again.", icon: ShieldCheck },
  { number: "02", title: "Cultural respect", detail: "Language opens a door, but respect teaches you how to enter a place with care.", icon: HeartHandshake },
  { number: "03", title: "Real outcomes", detail: "A certificate matters. So does the confidence to use Japanese in school, work, and everyday life.", icon: Sparkles },
];

export default function About() {
  return <SiteLayout>
    <section data-testid="about-hero" className="bg-[#a80000] px-5 pb-20 pt-40 text-[#fffaf2] md:px-10 md:pb-28 md:pt-48"><div className="mx-auto grid max-w-[1360px] gap-10 md:grid-cols-[.7fr_1.3fr] md:items-end"><p data-testid="about-hero-japanese" className="font-japanese text-8xl text-[#e7c36d]/70 md:text-[12rem]">人</p><div><p data-testid="about-hero-eyebrow" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[#e7c36d]">The person behind the path</p><h1 data-testid="about-hero-heading" className="mt-5 max-w-4xl font-display text-6xl leading-[.92] tracking-[-.06em] md:text-8xl">A guide who<br /><span className="text-[#e7c36d]">lives the journey.</span></h1><p data-testid="about-hero-copy" className="mt-7 max-w-xl text-sm leading-7 text-[#f7f1e8]/75">RSP in Japan began with a simple belief: students deserve an honest, human bridge between where they are and the life they are working toward.</p></div></div></section>
    <section data-testid="about-founder-section" className="wash-pattern px-5 py-24 md:px-10 md:py-32"><div className="mx-auto grid max-w-[1360px] gap-12 md:grid-cols-[.85fr_1.15fr] md:gap-20"><div><Placeholder label="[PLACEHOLDER: Rohit Shiv Prasad portrait]" aspect="portrait" /><div className="mt-4 flex items-center justify-between border-t border-[#a80000]/20 pt-4"><p data-testid="about-founder-caption" className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#a80000]">Founder · Rohit Shiv Prasad</p><span data-testid="about-founder-location" className="text-xs text-[#756862]">Kyoto, Japan</span></div></div><div className="md:pt-8"><SectionHeading eyebrow="About Rohit" title="The teacher who moved first." description="Rohit Shiv Prasad teaches with the clarity of someone who has crossed the distance himself — from India to Kyoto, from first conversations to a life built in Japan." /><div className="mt-10 grid gap-5 text-sm leading-7 text-[#756862] md:grid-cols-2"><p data-testid="about-founder-story-one">His classroom is practical, warm, and honest about the work. Japanese rewards consistency. It asks you to listen closely, respect the details, and return to the page even when the characters feel unfamiliar.</p><p data-testid="about-founder-story-two">That is the philosophy behind RSP in Japan: make the path visible, make the preparation personal, and keep showing up after the exciting beginning has passed.</p></div><a href="https://www.linkedin.com" target="_blank" rel="noreferrer" data-testid="about-linkedin-bio-link" className="mt-10 flex max-w-xl items-center justify-between border border-[#a80000]/20 bg-[#fffaf2] p-5 transition-transform duration-200 hover:-translate-y-1"><span><span data-testid="about-linkedin-placeholder" className="block text-[10px] font-bold uppercase tracking-[0.18em] text-[#a80000]">[Insert LinkedIn bio]</span><span data-testid="about-linkedin-description" className="mt-2 block text-xs text-[#756862]">Founder background, education, and experience</span></span><ArrowUpRight size={17} className="text-[#a80000]" /></a></div></div></section>
    <section data-testid="about-qualification-section" className="bg-[#fffaf2] px-5 py-20 md:px-10"><div className="mx-auto grid max-w-[1120px] items-center gap-10 border-y border-[#a80000]/20 py-10 md:grid-cols-[.8fr_1.2fr]"><div><p data-testid="about-qualification-eyebrow" className="text-[10px] font-bold uppercase tracking-[0.24em] text-[#a80000]">Proof in the practice</p><h2 data-testid="about-qualification-heading" className="mt-4 font-display text-4xl tracking-[-.04em] md:text-5xl">A teacher keeps learning too.</h2><p data-testid="about-qualification-copy" className="mt-5 text-sm leading-7 text-[#756862]">Rohit's own qualifications are part of the trust he builds with every student. Add the original certificate here when the final brand assets are ready.</p></div><div><Placeholder label="[PLACEHOLDER: Rohit's Japanese qualification certificate]" aspect="landscape" /><p data-testid="about-qualification-caption" className="mt-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.15em] text-[#756862]"><Award size={14} className="text-[#a80000]" /> Founder certificate / qualification · image to be added</p></div></div></section>
    <section data-testid="about-company-section" className="bg-[#a80000] px-5 py-24 text-[#fffaf2] md:px-10 md:py-32"><div className="mx-auto max-w-[1360px]"><SectionHeading light eyebrow="About the company" title="Five years of turning intention into movement." description="Founded in 2020, RSP in Japan has helped more than 50 students move toward Yokohama language school, JLPT progression from N3 to N1, and new work possibilities in Japan." /><div className="mt-16 max-w-4xl border-l border-[#f7f1e8]/25">{timeline.map((item, index) => <div key={item.year} data-testid={`about-timeline-${index}`} className="relative grid gap-2 border-b border-[#f7f1e8]/15 px-7 py-7 last:border-0 md:grid-cols-[120px_1fr] md:gap-8"><span className="absolute -left-[5px] top-9 h-2 w-2 rounded-full bg-[#e7c36d] ring-4 ring-[#a80000]" /><p data-testid={`about-timeline-year-${index}`} className="font-display text-2xl text-[#e7c36d]">{item.year}</p><div><h3 data-testid={`about-timeline-title-${index}`} className="font-display text-2xl">{item.title}</h3><p data-testid={`about-timeline-detail-${index}`} className="mt-2 text-sm leading-7 text-[#f7f1e8]/65">{item.detail}</p></div></div>)}</div></div></section>
    <section data-testid="about-values-section" className="wash-pattern px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1360px]"><SectionHeading eyebrow="What we believe" title="The values that keep the path real." /><div className="mt-14 grid gap-5 md:grid-cols-3">{values.map(({ number, title, detail, icon: ValueIcon }) => <article key={number} data-testid={`about-value-card-${number}`} className="border-t border-[#a80000]/25 pt-5"><div className="flex justify-between"><ValueIcon size={21} className="text-[#a80000]" /><span className="font-display text-3xl text-[#a80000]/25">{number}</span></div><h3 data-testid={`about-value-title-${number}`} className="mt-14 font-display text-3xl">{title}</h3><p data-testid={`about-value-detail-${number}`} className="mt-4 text-sm leading-7 text-[#756862]">{detail}</p></article>)}</div></div></section>
  </SiteLayout>;
}