import { ArrowRight, Check, Clock3, GraduationCap, Laptop, MapPin, UsersRound } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { Link } from "react-router-dom";
import SectionHeading from "@/components/site/SectionHeading";
import SiteLayout from "@/components/site/SiteLayout";
import { courseLevels } from "@/lib/site";

const formats: Array<{ icon: LucideIcon; title: string; detail: string }> = [{ icon: Laptop, title: "Online", detail: "A focused desk and a class that travels with you." }, { icon: MapPin, title: "Offline in Meerut", detail: "Learn in a room with people who are walking beside you." }, { icon: Clock3, title: "Weekend batches", detail: "Keep your weekdays moving while Japanese becomes part of your rhythm." }, { icon: UsersRound, title: "One-on-one intensive", detail: "A closer plan for a faster, more personal climb." }];
const pathway = ["Learn Japanese with RSP", "Reach N3", "Admission to Yokohama", "Study in Japan", "Advance to N2 / N1", "Job placement in Japan"];

export default function Courses() {
  return <SiteLayout>
    <section data-testid="courses-hero" className="bg-[#241b18] px-5 pb-20 pt-40 text-[#fffaf2] md:px-10 md:pb-28 md:pt-48"><div className="mx-auto max-w-[1360px]"><p data-testid="courses-hero-eyebrow" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[#e7c36d]">Courses + programs · 学ぶ</p><h1 data-testid="courses-hero-heading" className="mt-5 max-w-5xl font-display text-6xl leading-[.9] tracking-[-.06em] md:text-8xl">The language<br /><span className="text-[#e7c36d]">for what comes next.</span></h1><p data-testid="courses-hero-copy" className="mt-8 max-w-xl text-sm leading-7 text-[#f7f1e8]/70">A structured route from the first character to the Japanese you need for school, interviews, work, and a life that feels like your own.</p></div></section>
    <section data-testid="courses-levels-section" className="wash-pattern px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1360px]"><SectionHeading eyebrow="Choose your level" title="Meet the version of Japanese you are ready for." description="Start where you are. Move at a pace you can sustain. Ask about fees, placement, and the best fit for your goal." /><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{courseLevels.map((course, index) => <article key={course.level} data-testid={`course-level-card-${course.level.toLowerCase()}`} className={`group flex flex-col border border-[#a80000]/20 bg-[#fffaf2] p-6 transition-[transform,box-shadow] duration-300 hover:-translate-y-2 hover:shadow-xl ${index === 2 ? "border-[#a80000]" : ""}`}><div className="flex items-start justify-between"><span data-testid={`course-level-badge-${course.level.toLowerCase()}`} className="font-display text-5xl text-[#a80000]">{course.level}</span><span data-testid={`course-level-index-${course.level.toLowerCase()}`} className="text-[10px] font-bold tracking-[0.16em] text-[#a80000]/45">0{index + 1}</span></div><div className="mt-10 border-t border-[#a80000]/15 pt-4"><p data-testid={`course-duration-${course.level.toLowerCase()}`} className="flex items-center gap-2 text-xs font-bold"><Clock3 size={13} className="text-[#a80000]" />{course.duration}</p><p data-testid={`course-hours-${course.level.toLowerCase()}`} className="mt-2 text-[10px] uppercase tracking-[0.14em] text-[#756862]">{course.hours}</p></div><p data-testid={`course-detail-${course.level.toLowerCase()}`} className="mt-5 flex-1 text-sm leading-7 text-[#756862]">{course.detail}</p><Link to="/success-stories#contact" data-testid={`course-enquire-${course.level.toLowerCase()}-button`} className="mt-8 inline-flex items-center justify-between border-t border-[#a80000]/20 pt-4 text-[10px] font-bold uppercase tracking-[0.15em] text-[#a80000]">[ENQUIRE] <ArrowRight size={14} /></Link></article>)}</div></div></section>
    <section data-testid="courses-formats-section" className="bg-[#fffaf2] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto grid max-w-[1360px] gap-14 md:grid-cols-[.65fr_1.35fr]"><SectionHeading eyebrow="Batch formats" title="A format that fits your real life." description="Consistency becomes easier when the class respects the life you are already living." /> <div className="grid gap-px bg-[#a80000]/20 sm:grid-cols-2">{formats.map(({ icon: FormatIcon, title, detail }, index) => <article key={title} data-testid={`course-format-card-${index}`} className="bg-[#f7f1e8] p-7"><FormatIcon data-testid={`course-format-icon-${index}`} size={21} className="text-[#a80000]" /><h3 data-testid={`course-format-title-${index}`} className="mt-12 font-display text-2xl">{title}</h3><p data-testid={`course-format-detail-${index}`} className="mt-3 text-sm leading-7 text-[#756862]">{detail}</p></article>)}</div></div></section>
    <section data-testid="courses-included-section" className="bg-[#a80000] px-5 py-24 text-[#fffaf2] md:px-10 md:py-32"><div className="mx-auto grid max-w-[1360px] gap-14 md:grid-cols-[1fr_.9fr]"><div><SectionHeading light eyebrow="Inside every program" title="Practice for the exam. Prepare for the person you become." /><div className="mt-10 grid gap-3 sm:grid-cols-2">{["Study material that stays useful", "Kanji drills that build memory", "Speaking practice with Japan-based guidance", "Interview and keigo training", "JLPT mock tests with feedback", "A plan you can explain to your family"].map((item, index) => <div key={item} data-testid={`course-included-item-${index}`} className="flex items-start gap-3 border-t border-[#f7f1e8]/20 py-4 text-sm text-[#f7f1e8]/80"><Check size={16} className="mt-0.5 shrink-0 text-[#e7c36d]" />{item}</div>)}</div></div><div className="border-l border-[#f7f1e8]/20 pl-8"><GraduationCap data-testid="course-jlpt-icon" size={28} className="text-[#e7c36d]" /><h3 data-testid="course-jlpt-heading" className="mt-12 font-display text-4xl">JLPT preparation<br />with a mock-test mindset.</h3><p data-testid="course-jlpt-copy" className="mt-5 text-sm leading-7 text-[#f7f1e8]/70">Know what the exam is asking. Learn how to manage time, recognize patterns, and turn a practice score into a next step.</p><Link to="/success-stories#contact" data-testid="course-jlpt-inquiry-link" className="mt-8 inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.18em] text-[#e7c36d]">Ask about preparation <ArrowRight size={15} /></Link></div></div></section>
    <section data-testid="courses-pathway-section" className="wash-pattern px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1360px]"><SectionHeading eyebrow="The pathway" title="One clear direction. Many meaningful milestones." /><div className="mt-14 grid gap-3 md:grid-cols-6">{pathway.map((item, index) => <div key={item} data-testid={`course-pathway-step-${index}`} className="relative border-t border-[#a80000]/30 pt-5 md:border-t-0 md:border-l md:pl-5"><span data-testid={`course-pathway-number-${index}`} className="font-display text-3xl text-[#a80000]">0{index + 1}</span><p data-testid={`course-pathway-label-${index}`} className="mt-10 max-w-[130px] text-xs font-bold leading-5">{item}</p>{index < pathway.length - 1 && <ArrowRight data-testid={`course-pathway-arrow-${index}`} size={15} className="absolute right-3 top-7 hidden text-[#d5a33e] md:block" />}</div>)}</div></div></section>
  </SiteLayout>;
}