import { ArrowRight, BookOpen, FileCheck, HeartHandshake, MapPin, Route } from "lucide-react";
import { Link } from "react-router-dom";
import Placeholder from "@/components/site/Placeholder";
import SectionHeading from "@/components/site/SectionHeading";
import SiteLayout from "@/components/site/SiteLayout";
import { founderPhotoUrl } from "@/lib/site";

const whyCards = [
  { icon: BookOpen, number: "01", title: "Teaching with depth", detail: "From the first kana to N1, learn with structure, patient correction, and a teacher who understands the exam and the life beyond it." },
  { icon: Route, number: "02", title: "A direct pathway", detail: "Move with clarity toward Yokohama language school, with every milestone explained before you take the next step." },
  { icon: FileCheck, number: "03", title: "Guidance that stays", detail: "Documents, visa preparation, interviews, and the small questions families should never have to face alone." },
  { icon: HeartHandshake, number: "04", title: "Support from Japan", detail: "Rohit lives in Kyoto. Your support does not end when you leave India — it simply changes shape." },
];
const places = [
  { name: "Kyoto", caption: "Find a slower rhythm. Notice more.", className: "md:col-span-5 md:row-span-2", label: "[PLACEHOLDER: Kyoto streets and RSP founder life]" },
  { name: "Yokohama", caption: "Study close to the energy of the bay.", className: "md:col-span-7", label: "[PLACEHOLDER: Yokohama school and waterfront]" },
  { name: "Student life", caption: "Build routines that become your own.", className: "md:col-span-3", label: "[PLACEHOLDER: Student daily life in Japan]" },
  { name: "Tokyo", caption: "A wider world, one train at a time.", className: "md:col-span-4", label: "[PLACEHOLDER: Tokyo city life]" },
];

export default function Home() {
  return <SiteLayout>
    <section data-testid="home-hero" className="seigaiha relative overflow-hidden bg-[#a80000] px-5 pb-20 pt-36 text-[#fffaf2] md:px-10 md:pb-32 md:pt-48">
      <svg aria-hidden="true" className="absolute h-0 w-0">
        <defs>
          <filter id="home-remove-white" colorInterpolationFilters="sRGB">
            <feColorMatrix type="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  -1 -1 -1 3 0" />
          </filter>
        </defs>
      </svg>
      <div className="absolute -right-24 top-28 hidden font-japanese text-[18rem] leading-none text-[#f7f1e8]/[.07] lg:block">日</div>
      <div className="relative z-10 mx-auto grid max-w-[1360px] items-end gap-14 md:grid-cols-[1.1fr_.9fr]">
        <div className="max-w-3xl"><p data-testid="home-hero-eyebrow" className="reveal mb-6 flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.3em] text-[#e7c36d]"><span className="h-px w-12 bg-[#e7c36d]" />日本語への道 · A road to Japan</p><h1 data-testid="home-hero-heading" className="reveal reveal-delay-1 font-display text-[clamp(3.7rem,8vw,8.5rem)] leading-[.88] tracking-[-.07em]">Learn Japanese.<br /><span className="text-[#e7c36d]">Live Japan.</span></h1><p data-testid="home-hero-copy" className="reveal reveal-delay-2 mt-9 max-w-xl text-base leading-8 text-[#f7f1e8]/80 md:text-lg">Learn Japanese in Japan.</p><div className="reveal reveal-delay-3 mt-10 flex flex-col gap-3 sm:flex-row"><Link to="/courses" data-testid="home-start-learning-button" className="group inline-flex items-center justify-center gap-3 bg-[#e7c36d] px-6 py-4 text-[10px] font-bold uppercase tracking-[0.16em] text-[#241b18] transition-transform duration-200 hover:-translate-y-1">Start learning Japanese <ArrowRight size={15} className="transition-transform duration-200 group-hover:translate-x-1" /></Link><Link to="/success-stories#contact" data-testid="home-talk-rohit-button" className="inline-flex items-center justify-center gap-3 border border-[#f7f1e8]/35 px-6 py-4 text-[10px] font-bold uppercase tracking-[0.16em] transition-colors duration-200 hover:border-[#e7c36d] hover:text-[#e7c36d]">Talk to Rohit <ArrowRight size={15} /></Link></div></div>
        <div className="md:pb-2"><div className="mb-7 overflow-hidden rounded-sm md:ml-auto md:max-w-sm"><img src={founderPhotoUrl} alt="Rohit Shiv Prasad, founder of RSP in Japan" data-testid="home-founder-photo" className="h-56 w-full object-contain object-bottom md:h-64" style={{ filter: "url(#home-remove-white)" }} /></div><div className="border-l border-[#f7f1e8]/25 pl-6 md:ml-auto md:max-w-sm"><p data-testid="home-founder-label" className="text-[10px] font-bold uppercase tracking-[0.24em] text-[#e7c36d]">RSP in Japan</p><p data-testid="home-founder-name" className="mt-4 font-display text-4xl leading-tight">Study Japanese in Japan.<br />A life in Tokyo.</p><p data-testid="home-founder-location" className="mt-5 flex items-center gap-2 text-sm text-[#f7f1e8]/65"><MapPin size={14} className="text-[#e7c36d]" /> Founded by Rohit Shiv Prasad · Kyoto, Japan</p><Link to="/founder" data-testid="home-founder-page-link" className="mt-6 inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.18em] text-[#e7c36d] transition-colors duration-200 hover:text-[#fffaf2]">Meet the founder <ArrowRight size={14} /></Link></div></div>
      </div><div className="mx-auto mt-20 max-w-[1360px] border-t border-[#f7f1e8]/20 pt-6"><p data-testid="home-scroll-label" className="flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.25em] text-[#f7f1e8]/60"><span className="h-8 w-px bg-[#e7c36d]" />Scroll to begin</p></div>
    </section>
    <section data-testid="home-trust-strip" className="bg-[#241b18] px-5 py-10 text-[#f7f1e8] md:px-10"><div className="mx-auto grid max-w-[1360px] divide-y divide-[#f7f1e8]/15 sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4">{[["5+", "years of guidance", "Since 2020"], ["50+", "students in Japan", "And counting"], ["N3 → N1", "levels achieved", "With intention"], ["Japan", "jobs in sight", "Beyond the classroom"]].map(([stat, label, note]) => <div key={stat} data-testid={`home-trust-stat-${stat.replace(/[^a-z0-9]+/gi, "-")}`} className="px-5 py-5 first:pl-0 sm:px-8 lg:py-2"><p className="font-display text-4xl text-[#e7c36d] md:text-5xl">{stat}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-[0.16em]">{label}</p><p className="mt-1 text-xs text-[#f7f1e8]/45">{note}</p></div>)}</div></section>
    <section data-testid="home-why-section" className="wash-pattern px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1360px]"><SectionHeading eyebrow="Why RSP in Japan" title="Language is the beginning. The relationship is the difference." description="Learning Japanese is not just a subject on a timetable. It is discipline, cultural respect, and a future that asks you to keep showing up." /><div className="mt-14 grid gap-px overflow-hidden border border-[#a80000]/15 bg-[#a80000]/15 md:grid-cols-2 lg:grid-cols-4">{whyCards.map(({ icon: Icon, ...card }) => <article key={card.number} data-testid={`home-why-card-${card.number}`} className="group bg-[#fffaf2] p-8 transition-[transform,box-shadow] duration-300 hover:-translate-y-2 hover:shadow-xl md:min-h-[300px]"><div className="flex items-start justify-between"><Icon data-testid={`home-why-icon-${card.number}`} size={21} strokeWidth={1.5} className="text-[#a80000]" /><span data-testid={`home-why-number-${card.number}`} className="font-display text-3xl text-[#a80000]/25">{card.number}</span></div><h3 data-testid={`home-why-title-${card.number}`} className="mt-16 font-display text-2xl leading-tight">{card.title}</h3><p data-testid={`home-why-detail-${card.number}`} className="mt-4 text-sm leading-7 text-[#756862]">{card.detail}</p></article>)}</div></div></section>
    <section data-testid="home-life-section" className="bg-[#a80000] px-5 py-24 text-[#fffaf2] md:px-10 md:py-32"><div className="mx-auto max-w-[1360px]"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading light eyebrow="Life in Japan" title="Picture the life you are learning for." description="Four places. A thousand small moments. The train ride, the classroom, the first conversation that feels like yours." /><span data-testid="home-life-japanese" className="font-japanese text-7xl text-[#f7f1e8]/20 md:text-9xl">暮らし</span></div><div className="mt-14 grid auto-rows-[190px] gap-3 md:grid-cols-12 md:auto-rows-[170px]">{places.map((place, index) => <div key={place.name} data-testid={`home-life-placeholder-${place.name.toLowerCase().replace(" ", "-")}`} className={`relative overflow-hidden ${place.className}`}><Placeholder label={place.label} dark className="h-full rounded-none" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#241b18]/80 to-transparent px-5 pb-5 pt-12"><p data-testid={`home-life-name-${index}`} className="font-display text-2xl">{place.name}</p><p data-testid={`home-life-caption-${index}`} className="mt-1 text-xs text-[#f7f1e8]/70">{place.caption}</p></div></div>)}</div></div></section>
    <section data-testid="home-results-section" className="bg-[#f7f1e8] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1360px]"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading eyebrow="Student results" title="Small wins become a different life." description="Every certificate carries a story of practice, patience, and someone back home who kept believing." /><Link to="/success-stories" data-testid="home-view-stories-link" className="group inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.18em] text-[#a80000]">Read their stories <ArrowRight size={15} className="transition-transform duration-200 group-hover:translate-x-1" /></Link></div><div className="mt-14 grid gap-5 md:grid-cols-3">{[["01", "From N3 to Yokohama", "The language milestone that opened the application door."], ["02", "A first N1", "Advanced Japanese earned one disciplined day at a time."], ["03", "Work begins here", "Preparing for the interview, not just the exam."]].map(([num, title, detail]) => <article key={num} data-testid={`home-result-card-${num}`} className="border-t border-[#a80000]/25 pt-5"><span data-testid={`home-result-number-${num}`} className="text-[10px] font-bold tracking-[0.2em] text-[#a80000]">{num}</span><h3 data-testid={`home-result-title-${num}`} className="mt-10 font-display text-3xl leading-tight">{title}</h3><p data-testid={`home-result-detail-${num}`} className="mt-4 text-sm leading-7 text-[#756862]">{detail}</p></article>)}</div></div></section>
    <section data-testid="home-cta-section" className="seigaiha bg-[#241b18] px-5 py-24 text-[#f7f1e8] md:px-10 md:py-32"><div className="mx-auto flex max-w-[1360px] flex-col justify-between gap-10 md:flex-row md:items-end"><div><p data-testid="home-cta-eyebrow" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[#e7c36d]">Your next chapter</p><h2 data-testid="home-cta-heading" className="mt-5 max-w-3xl font-display text-5xl leading-[.95] tracking-[-.05em] md:text-7xl">The road to Japan<br /><span className="text-[#e7c36d]">starts in your classroom.</span></h2></div><Link to="/success-stories#contact" data-testid="home-cta-inquiry-button" className="inline-flex shrink-0 items-center justify-center gap-3 bg-[#e7c36d] px-6 py-4 text-[10px] font-bold uppercase tracking-[0.16em] text-[#241b18] transition-transform duration-200 hover:-translate-y-1">Make an inquiry <ArrowRight size={15} /></Link></div></section>
  </SiteLayout>;
}