import { ArrowRight, BriefcaseBusiness, Coins, Home, Plane, TrainFront, Utensils, UsersRound } from "lucide-react";
import { Link } from "react-router-dom";
import type { LucideIcon } from "lucide-react";
import Placeholder from "@/components/site/Placeholder";
import SectionHeading from "@/components/site/SectionHeading";
import SiteLayout from "@/components/site/SiteLayout";
import { steps } from "@/lib/site";

const practicals: Array<{ icon: LucideIcon; title: string; detail: string }> = [{ icon: Home, title: "Accommodation", detail: "Understand your options before the suitcase is packed." }, { icon: Coins, title: "Cost of living", detail: "Plan for the everyday with a realistic, grounded picture." }, { icon: TrainFront, title: "Transport", detail: "Learn the rhythms of trains, routes, and getting around." }, { icon: Utensils, title: "Culture tips", detail: "Small gestures make a new place feel more welcoming." }];
const placementRoles: Array<{ icon: LucideIcon | typeof GraduationCapIcon; title: string }> = [{ icon: BriefcaseBusiness, title: "Business and office roles" }, { icon: UsersRound, title: "Care and service roles" }, { icon: Plane, title: "Hospitality and tourism" }, { icon: GraduationCapIcon, title: "Further study pathways" }];
const galleries = [["[PLACEHOLDER: Student at Yokohama station]", "Your first route home"], ["[PLACEHOLDER: Student classroom in Japan]", "Learning in a new room"], ["[PLACEHOLDER: Students exploring Japan]", "The weekends become yours"]];

export default function StudyInJapan() {
  return <SiteLayout>
    <section data-testid="study-hero" className="bg-[#a80000] px-5 pb-20 pt-40 text-[#fffaf2] md:px-10 md:pb-28 md:pt-48"><div className="mx-auto grid max-w-[1360px] gap-12 md:grid-cols-[1.15fr_.85fr] md:items-end"><div><p data-testid="study-hero-eyebrow" className="text-[10px] font-bold uppercase tracking-[0.28em] text-[#e7c36d]">Study in Japan · 日本で学ぶ</p><h1 data-testid="study-hero-heading" className="mt-5 max-w-4xl font-display text-6xl leading-[.9] tracking-[-.06em] md:text-8xl">The next step<br /><span className="text-[#e7c36d]">has a place.</span></h1><p data-testid="study-hero-copy" className="mt-8 max-w-xl text-sm leading-7 text-[#f7f1e8]/75">Yokohama language school gives your Japanese a new context: a classroom, a neighbourhood, and a city where you can begin making the language yours.</p></div><Placeholder label="[PLACEHOLDER: Yokohama language school / city view]" dark aspect="portrait" /></div></section>
    <section data-testid="study-school-section" className="wash-pattern px-5 py-24 md:px-10 md:py-32"><div className="mx-auto grid max-w-[1360px] gap-14 md:grid-cols-[.8fr_1.2fr] md:items-center"><Placeholder label="[PLACEHOLDER: Yokohama Design College / language school exterior]" aspect="landscape" /><div><SectionHeading eyebrow="The partner pathway" title="Yokohama, where the next chapter gets real." description="A language school is more than a destination. It is the place where your study routine, friendships, independence, and Japanese start to belong together." /><div className="mt-10 grid gap-4 border-t border-[#a80000]/20 pt-5 sm:grid-cols-3">{[["01", "A focused environment"], ["02", "A city with momentum"], ["03", "A bridge to work"]].map(([number, title]) => <div key={number} data-testid={`study-school-point-${number}`}><span className="font-display text-2xl text-[#a80000]">{number}</span><p data-testid={`study-school-point-title-${number}`} className="mt-5 text-xs font-bold leading-5">{title}</p></div>)}</div></div></div></section>
    <section data-testid="study-steps-section" className="bg-[#fffaf2] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1360px]"><SectionHeading eyebrow="Your route to Japan" title="Eight steps. No mystery." description="We keep the process visible so you can focus on the work that matters — becoming ready for the life ahead." /><div className="mt-16 grid max-w-4xl gap-0 border-l border-[#a80000]/25 md:ml-16">{steps.map((step, index) => <article key={step.number} data-testid={`study-step-${index}`} className="relative grid gap-3 border-b border-[#a80000]/15 px-7 py-7 last:border-0 md:grid-cols-[80px_190px_1fr] md:items-start md:gap-6"><span className="absolute -left-[5px] top-9 h-2 w-2 rounded-full bg-[#a80000] ring-4 ring-[#fffaf2]" /><span data-testid={`study-step-number-${index}`} className="font-display text-2xl text-[#a80000]">{step.number}</span><h3 data-testid={`study-step-title-${index}`} className="font-display text-2xl">{step.title}</h3><p data-testid={`study-step-detail-${index}`} className="text-sm leading-7 text-[#756862]">{step.detail}</p></article>)}</div></div></section>
    <section data-testid="study-practicals-section" className="bg-[#241b18] px-5 py-24 text-[#fffaf2] md:px-10 md:py-32"><div className="mx-auto max-w-[1360px]"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading light eyebrow="Living in Japan" title="The practical things matter." description="A good move is made of small preparations. We help you think beyond admission and into the everyday." /><span data-testid="study-practicals-japanese" className="font-japanese text-7xl text-[#f7f1e8]/10">暮らす</span></div><div className="mt-14 grid gap-px bg-[#f7f1e8]/15 sm:grid-cols-2 lg:grid-cols-4">{practicals.map(({ icon: PracticalIcon, title, detail }, index) => <article key={title} data-testid={`study-practical-card-${index}`} className="bg-[#241b18] p-7"><PracticalIcon data-testid={`study-practical-icon-${index}`} size={22} className="text-[#e7c36d]" /><h3 data-testid={`study-practical-title-${index}`} className="mt-14 font-display text-2xl">{title}</h3><p data-testid={`study-practical-detail-${index}`} className="mt-3 text-sm leading-7 text-[#f7f1e8]/55">{detail}</p></article>)}</div></div></section>
    <section data-testid="study-placement-section" className="bg-[#f7f1e8] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto grid max-w-[1360px] gap-14 md:grid-cols-[1.1fr_.9fr]"><div><SectionHeading eyebrow="Beyond the classroom" title="Prepare for the work that follows." description="After N2 or N1, Japanese can become the language of your professional life. We help you prepare for that conversation." /><div className="mt-10 grid gap-3 sm:grid-cols-2">{placementRoles.map(({ icon: PlacementIcon, title }, index) => <div key={title} data-testid={`study-placement-role-${index}`} className="flex items-center gap-4 border-t border-[#a80000]/20 py-4"><PlacementIcon size={18} className="text-[#a80000]" /><span data-testid={`study-placement-role-title-${index}`} className="text-sm font-bold">{title}</span></div>)}</div></div><div className="border-l border-[#a80000]/20 pl-8 md:pt-8"><p data-testid="study-placement-support-eyebrow" className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#a80000]">Our support</p><p data-testid="study-placement-support-copy" className="mt-5 font-display text-4xl leading-tight">A Japanese interview needs more than memorised answers.</p><p data-testid="study-placement-support-detail" className="mt-5 text-sm leading-7 text-[#756862]">Practice your story, refine your keigo, understand the room, and walk in carrying the confidence of preparation.</p><Link to="/success-stories#contact" data-testid="study-placement-contact-link" className="mt-8 inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.18em] text-[#a80000]">Talk through your goal <ArrowRight size={15} /></Link></div></div></section>
    <section data-testid="study-gallery-section" className="bg-[#a80000] px-5 py-24 text-[#fffaf2] md:px-10 md:py-32"><div className="mx-auto max-w-[1360px]"><SectionHeading light eyebrow="Student life" title="The photos you will make here." /><div className="mt-14 grid gap-4 md:grid-cols-3">{galleries.map(([label, caption], index) => <div key={caption} data-testid={`study-gallery-item-${index}`}><Placeholder label={label} dark aspect={index === 1 ? "portrait" : "landscape"} /><p data-testid={`study-gallery-caption-${index}`} className="mt-4 font-display text-2xl">{caption}</p></div>)}</div></div></section>
  </SiteLayout>;
}

function GraduationCapIcon(props: { size?: number; className?: string }) { return <GraduationCapFallback {...props} />; }
function GraduationCapFallback({ size = 22, className = "" }: { size?: number; className?: string }) { return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className={className}><path d="m2 10 10-5 10 5-10 5-10-5Z" /><path d="M6 12v5c3 2 9 2 12 0v-5M22 10v6" /></svg>; }